version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres_om30
    restart: always
    environment:
      POSTGRES_PASSWORD: <%= ENV.fetch("password") %>
      POSTGRES_INITDB_ARGS: "--data-checksums"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pgconf:/docker-entrypoint-initdb.d/

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
