name: ruby-test-OM30

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_USER: postgres
      DATABASE_PASSWORD: aleatorio123
      DATABASE_HOST: localhost
      DATABASE_URL: postgresql://postgres:aleatorio123@localhost/om30_project_test

    services:
      db:
        image: postgres
        ports: [ "5432:5432" ]
        env:
          POSTGRES_DB: om30_project_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: aleatorio123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.1'

      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev
          bundle install 
          bundle exec rails db:migrate
          bundle exec rails db:seed

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Yarn
        run: |
          npm install yarn
          yarn --version
          yarn install
 

      - name: Run Tests (rspec)
        run: |
          bundle exec rspec
