name: ruby-test-OM30
  on: push
    jobs:
      rubocop:
        name: Rubocop
        runs-on: ubuntu-20.04
        steps:
          - name: Checkout code
            uses: actions/checkout@v1

          - name: Setup Ruby
            uses: ruby/setup-ruby@v1
            with:
              bundler-cache: true

          - name: Analyze code
            run: bundle exec rubocop

      rspec:
        name: RSpec
        needs: rubocop
        runs-on: ubuntu-20.04
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/om30_project_test
        services:
          postgres:
            image: postgres:latest
            ports: [ '5432:5432' ]
            env:
              POSTGRES_DB: om30_project_test
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: aleatoriamente123
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
          - name: Checkout code
            uses: actions/checkout@v1

          - name: Setup Ruby
            uses: ruby/setup-ruby@v1
            with:
              bundler-cache: true

          - name: Install postgres client dependencies
            run: sudo apt-get install libpq-dev

          - name: Setup Node
            uses: actions/setup-node@v1
            with:
              node-version: 16.0.x

          - name: Yarn package cache
            uses: actions/cache@v2
            with:
              path: ./node_modules
              key: ${{ runner.os }}-yarn-v1-${{ hashFiles('./yarn.lock') }}

          - name: Install Yarn packages
            run: yarn install --pure-lockfile

          - name: Create database
            run: |
              bundle exec rails db:create
              bundle exec rails db:schema:load
              bundle exec rails db:structure:load
              bundle exec rails db:migrate

          - name: Run tests
            run: bundle exec rspec spec
