name: ruby-test-OM30

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_USER: postgres
      DATABASE_PASSWORD: aleatorio123
      DATABASE_HOST: localhost
      DATABASE_URL: postgresql://postgres:aleatorio123@localhost/om30_project_test

    services:
      db:
        image: postgres
        ports: [ "5432:5432" ]
        env:
          POSTGRES_DB: om30_project_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: aleatorio123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.14.0

      - name: Yarn package cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('./yarn.lock') }}

      - name: Install Yarn packages
        run: yarn install --pure-lockfile


      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.1.3"

      - name: Run Install
        run: |
          sudo apt-get -yqq install libpq-dev
          gem update --system
          gem install rake -v 13.0.1
          gem install bundler -v "2.4.8"
          bundle install
          bundle update --bundler
          bundle rails db:seed
          bundle rails db:migrate
          rails assets:precompile


      - name: Run Tests (rspec)
        run: |
          bundle exec rspec